"""Export paper-ready LaTeX snippets for scaffold experiments."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
IN_SUMMARY = ROOT / "analysis/overnight_runs/scaffold_fusion_dim64_summary.json"
IN_CONSERVATIVE = ROOT / "analysis/overnight_runs/scaffold_fusion_dim64_margin002_summary.json"
IN_MARGIN = ROOT / "analysis/overnight_runs/scaffold_margin_sweep.json"
OUT = ROOT / "analysis/overnight_runs/scaffold_tables.tex"


def pct(x):
    return f"{100 * x:.1f}"


def pp(x):
    return f"{100 * x:+.2f}"


def main():
    summary = json.loads(IN_SUMMARY.read_text())["summary"]
    conservative = json.loads(IN_CONSERVATIVE.read_text())["summary"]
    margin = json.loads(IN_MARGIN.read_text())

    lines = []
    lines.append("% Auto-generated by analysis/export_scaffold_tables.py")
    lines.append("% Scaffold overall summary")
    lines.append("\\begin{tabular}{lrrrr}")
    lines.append("\\toprule")
    lines.append("Setting & N & Mean $\\Delta$ & Median $\\Delta$ & Win Rate \\\\")
    lines.append("\\midrule")
    for setting, s in summary.items():
        d = s["delta_vs_val_single"]
        label = "Response correctness" if setting == "new" else "Dataset label"
        lines.append(
            f"{label} & {s['n']} & {pp(d['mean'])} & {pp(d['median'])} & {pct(d['positive_rate'])} \\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("")
    lines.append("% Actual conservative scaffold run")
    lines.append("\\begin{tabular}{lrrrr}")
    lines.append("\\toprule")
    lines.append("Setting & Margin $\\gamma$ & Mean $\\Delta$ & Min $\\Delta$ & Win Rate \\\\")
    lines.append("\\midrule")
    d = conservative["new"]["delta_vs_val_single"]
    lines.append(
        f"Response correctness & 0.02 & {pp(d['mean'])} & {pp(d['min'])} & {pct(d['positive_rate'])} \\\\"
    )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("")

    lines.append("% Scaffold capacity/margin policy summary")
    lines.append("\\begin{tabular}{lrrrr}")
    lines.append("\\toprule")
    lines.append("Setting & Margin $\\gamma$ & Mean $\\Delta$ & Min $\\Delta$ & Win Rate \\\\")
    lines.append("\\midrule")
    for r in margin:
        if r["margin"] not in [0, 0.02]:
            continue
        label = "Response correctness" if r["setting"] == "new" else "Dataset label"
        lines.append(
            f"{label} & {r['margin']:.2f} & {pp(r['mean_delta_vs_val_single'])} & "
            f"{pp(r['min_delta_vs_val_single'])} & {pct(r['win_rate_vs_val_single'])} \\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
